"""Phase 15.0 — Understat connector (free, NO API key).

Understat publishes per-player expected-goals (xG) / expected-assists (xA),
shots, key passes and minutes. Two access paths are supported:

1. **HTML embedded JSON** (the technique used by the public ``understat``
   package): league/player pages embed their datasets as hex-encoded strings
   passed to ``JSON.parse('...')`` inside inline ``<script>`` blocks. We locate
   each block with a regex, undo the ``\\xNN`` escapes (or literal-hex decode),
   then ``json.loads`` the payload.
2. **AJAX endpoint** ``POST /main/getPlayersStats/`` which returns plain JSON
   ``{"success": true, "players": [...]}`` per league+season — one call for
   all EPL players.

Politeness: browser User-Agent, >= 1 s between requests, cache-first with a
24 h TTL.

Because hosting platforms can be blocked upstream, a committed offline
snapshot (``data/seed/understat_snapshot.json``, generated by
``scripts/fetch_understat_snapshot.py`` where not blocked) always provides
last-season xG/xA; live fetches only enrich it when reachable and any failure
disables enrichment gracefully — never the request.
"""

from __future__ import annotations

import codecs
import json
import logging
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from fpl_intelligence.data_providers.base import (
    BaseDataConnector,
    DataConnectionError,
    DataParseError,
)

logger = logging.getLogger(__name__)

UNDERSTAT_BASE_URL = "https://understat.com"
UNDERSTAT_LEAGUE_URL = UNDERSTAT_BASE_URL + "/league/{league}/{season}"
UNDERSTAT_PLAYER_STATS_URL = UNDERSTAT_BASE_URL + "/main/getPlayersStats/"

#: Default committed snapshot written by scripts/fetch_understat_snapshot.py.
UNDERSTAT_SNAPSHOT_PATH = Path("data") / "seed" / "understat_snapshot.json"

#: Matches e.g.  var playersData = JSON.parse('\x7B\x5B...') ;
_HEX_JSON_BLOCK_RE = re.compile(r"JSON\.parse\('([0-9a-fA-F\\x]+)'\)")

BROWSER_HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    ),
    "Accept": "text/html,application/xhtml+xml,application/json;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-GB,en;q=0.9",
}


def decode_hex_json(raw: str) -> Any:
    """Decode an Understat hex-encoded ``JSON.parse`` payload into Python data.

    The page embeds payloads such as ``'\\x7B\\x22id\\x22...'`` — ASCII text of
    ``\\xNN`` escapes. ``bytes.decode("unicode_escape")`` restores the raw
    characters before ``json.loads`` parses them. Payloads that are already
    literal hex digits (no ``\\x`` prefixes) go through :func:`codecs.decode`.
    """
    text = raw.strip()
    if "\\x" in text:
        try:
            text = text.encode("ascii").decode("unicode_escape")
        except UnicodeDecodeError as exc:  # pragma: no cover - defensive
            raise DataParseError(f"Understat unicode_escape failed: {exc}") from exc
    elif re.fullmatch(r"[0-9a-fA-F]+", text):
        try:
            text = codecs.decode(text, "hex").decode("utf-8")
        except (ValueError, UnicodeDecodeError) as exc:
            raise DataParseError(f"Understat hex decode failed: {exc}") from exc
    try:
        return json.loads(text)
    except json.JSONDecodeError as exc:
        raise DataParseError(f"Understat embedded JSON invalid: {exc}") from exc


def parse_hex_json_blocks(html: str) -> dict[str, Any]:
    """Extract every ``var NAME = JSON.parse('<hex>')`` dataset from a page.

    Returns a mapping of variable name -> decoded object. Pages that embed no
    datasets (blocked/empty shells) yield an empty dict so callers degrade to
    the offline snapshot instead of crashing.
    """
    datasets: dict[str, Any] = {}
    for var_match in re.finditer(r"var\s+(\w+)\s*=\s*JSON\.parse\('([0-9a-fA-F\\x]+)'\)", html):
        name, raw = var_match.group(1), var_match.group(2)
        try:
            datasets[name] = decode_hex_json(raw)
        except DataParseError:
            logger.warning("Understat block %s could not be decoded", name)
    # Anonymous JSON.parse calls (pages that parse without a var declaration).
    if not datasets:
        for anon in _HEX_JSON_BLOCK_RE.finditer(html):
            try:
                datasets[f"block_{len(datasets)}"] = decode_hex_json(anon.group(1))
            except DataParseError:
                continue
    return datasets


@dataclass
class UnderstatPlayerStats:
    """Normalised per-player Understat season aggregates."""

    understat_id: str
    player_name: str
    team_title: str
    position: str
    minutes: int
    games: int
    goals: int
    assists: int
    xg: float
    xa: float
    shots: int
    key_passes: int
    #: Per-90 rates computed from minutes (division-safe).
    xg_per_90: float
    xa_per_90: float


def _to_float(value: Any) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return 0.0


def _to_int(value: Any) -> int:
    try:
        return int(float(value))
    except (TypeError, ValueError):
        return 0


def parse_players_stats_payload(payload: dict[str, Any]) -> list[UnderstatPlayerStats]:
    """Normalise the ``getPlayersStats`` JSON payload into stats objects."""
    players = payload.get("players") if isinstance(payload, dict) else None
    if not isinstance(players, list):
        raise DataParseError("Understat payload missing 'players' list")
    stats: list[UnderstatPlayerStats] = []
    for row in players:
        if not isinstance(row, dict):
            continue
        minutes = _to_int(row.get("time"))
        xg = _to_float(row.get("xG"))
        xa = _to_float(row.get("xA"))
        stats.append(
            UnderstatPlayerStats(
                understat_id=str(row.get("id", "")),
                player_name=str(row.get("player_name", "")),
                team_title=str(row.get("team_title", "")),
                position=str(row.get("position", "")),
                minutes=minutes,
                games=_to_int(row.get("games")),
                goals=_to_int(row.get("goals")),
                assists=_to_int(row.get("assists")),
                xg=xg,
                xa=xa,
                shots=_to_int(row.get("shots")),
                key_passes=_to_int(row.get("key_passes")),
                xg_per_90=(xg / minutes) * 90.0 if minutes > 0 else 0.0,
                xa_per_90=(xa / minutes) * 90.0 if minutes > 0 else 0.0,
            )
        )
    return stats


def build_stats_from_row(row: dict[str, Any]) -> UnderstatPlayerStats:
    """Build normalised stats from one raw snapshot/AJAX row."""
    return parse_players_stats_payload({"players": [row]})[0]


class UnderstatConnector(BaseDataConnector):
    """Cache-first Understat connector with a polite rate limit.

    All network access is mockable via ``http_client`` (``httpx.MockTransport``
    in tests); no live call is ever made inside pytest.
    """

    name = "understat"

    def __init__(
        self,
        *,
        base_url: str = UNDERSTAT_BASE_URL,
        cache: Any = None,
        http_client: Any = None,
        timeout: float = 20.0,
        headers: Any = None,
        min_interval_seconds: float = 1.0,
        clock: Any = None,
        monotonic_clock: Any = None,
        sleep: Any = None,
    ) -> None:
        super().__init__(
            base_url=base_url,
            cache=cache,
            http_client=http_client,
            timeout=timeout,
            headers=headers or BROWSER_HEADERS,
            min_interval_seconds=min_interval_seconds,
            clock=clock,
            monotonic_clock=monotonic_clock,
            sleep=sleep,
        )

    # -- live fetches ----------------------------------------------------------

    def fetch_league_page(self, league: str = "EPL", season: int = 2025) -> str:
        """Return the raw HTML of a league season page (hex datasets inside)."""
        url = UNDERSTAT_LEAGUE_URL.format(league=league.upper(), season=season)
        try:
            response = self._request("GET", url)
        except Exception as exc:  # noqa: BLE001
            raise DataConnectionError(f"Understat unreachable: {exc}") from exc
        if response.status_code != 200:
            raise DataConnectionError(f"Understat returned HTTP {response.status_code} for {url}")
        return response.text

    def fetch_league_datasets(self, league: str = "EPL", season: int = 2025) -> dict[str, Any]:
        """Fetch a league page and decode its embedded hex-JSON datasets."""
        html = self.fetch_league_page(league=league, season=season)
        return parse_hex_json_blocks(html)

    def fetch_players_stats(
        self, league: str = "EPL", season: int = 2025
    ) -> list[UnderstatPlayerStats]:
        """Fetch all players for a league+season via the AJAX endpoint.

        Failures surface as :class:`DataConnectionError` so callers can degrade
        to the offline snapshot; caching is handled by the shared response
        cache when one is wired in.
        """
        form = {
            "league": league.lower(),
            "season": str(season),
            "sortBy": "time",
            "orderBy": "-1",
        }
        try:
            response = self._client.post(UNDERSTAT_PLAYER_STATS_URL, data=form)
            response.raise_for_status()
            payload = response.json()
        except Exception as exc:  # noqa: BLE001
            raise DataConnectionError(f"Understat AJAX failed: {exc}") from exc
        return parse_players_stats_payload(payload)

    # -- offline snapshot ------------------------------------------------------

    @staticmethod
    def load_snapshot(path: Path | None = None) -> dict[str, list[dict[str, Any]]]:
        """Load the committed offline snapshot; empty dict when absent.

        Layout::

            {"meta": {...}, "seasons": {"2025": [player, ...], "2026": [...]}}

        A missing or unreadable snapshot is *not* an error — it only means no
        xG/xA enrichment from Understat this run.
        """
        resolved = (path or UNDERSTAT_SNAPSHOT_PATH).resolve()
        if not resolved.is_file():
            logger.info("Understat snapshot not found at %s; skipping", resolved)
            return {}
        try:
            data = json.loads(resolved.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            logger.warning("Understat snapshot unreadable (%s); skipping", exc)
            return {}
        seasons = data.get("seasons") if isinstance(data, dict) else None
        if not isinstance(seasons, dict):
            return {}
        return {
            str(season): [row for row in rows if isinstance(row, dict)]
            for season, rows in seasons.items()
            if isinstance(rows, list)
        }

    @staticmethod
    def snapshot_player_index(
        snapshot: dict[str, list[dict[str, Any]]],
    ) -> dict[str, dict[str, Any]]:
        """Flatten snapshot seasons into a name-indexed map (latest season wins)."""
        index: dict[str, dict[str, Any]] = {}
        for season in sorted(snapshot.keys()):
            for row in snapshot[season]:
                name = str(row.get("player_name", "")).strip().lower()
                if name:
                    index[name] = row
        return index

    @staticmethod
    def match_player(
        index: dict[str, dict[str, Any]],
        web_name: str,
        full_name_hint: str = "",
    ) -> dict[str, Any] | None:
        """Best-effort match of an FPL ``web_name`` against Understat names.

        Strategy: exact full-name match -> containment either way against the
        optional full-name hint -> unique surname-token match. Returns ``None``
        when nothing plausible matches; callers must treat that as "no
        enrichment", never guess.
        """
        needle = web_name.strip().lower()
        if not needle:
            return None
        if needle in index:
            return index[needle]
        hint = full_name_hint.strip().lower() or needle
        if hint != needle:
            for name, row in index.items():
                if hint in name or name in hint:
                    return row
        tokens = [t for t in re.split(r"[\s\-.']+", needle) if t]
        if tokens:
            surname = tokens[-1]
            candidates = {name: row for name, row in index.items() if surname in name.split()}
            if len(candidates) == 1:
                return next(iter(candidates.values()))
        return None
