"""Phase 4.5 Quantitative Edge Validation -- benchmark report generator.

Writes ``docs/phase4-5-quantitative-edge-report.md`` from the structured result
dict produced by ``validation.edge.run_full_gate``.
"""

from __future__ import annotations

import math
from datetime import datetime
from pathlib import Path
from typing import Any

REPORT_PATH = Path("docs") / "phase4-5-quantitative-edge-report.md"


def _f(val) -> str:
    if val is None or (isinstance(val, float) and math.isnan(val)):
        return "n/a"
    return f"{val:.4f}"


def _pct(val) -> str:
    if val is None or (isinstance(val, float) and math.isnan(val)):
        return "n/a"
    return f"{100 * val:.1f}%"


def _metro(metrics: dict[str, Any]) -> str:
    return (
        f"n={metrics.get('n', 'n/a')}, MAE={_f(metrics.get('mae'))}, "
        f"RMSE={_f(metrics.get('rmse'))}, Spearman={_f(metrics.get('spearman'))}, "
        f"top5={_pct(metrics.get('top5'))}, top10={_pct(metrics.get('top10'))}, "
        f"top20={_pct(metrics.get('top20'))}"
    )


def _model_table(metrics_by_model: dict[str, dict[str, Any]]) -> str:
    lines = [
        "| Model | n | MAE | RMSE | Spearman | top5 | top10 | top20 |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for m, met in metrics_by_model.items():
        lines.append(
            f"| {m} | {met.get('n', 'n/a')} | {_f(met.get('mae'))} | "
            f"{_f(met.get('rmse'))} | {_f(met.get('spearman'))} | "
            f"{_pct(met.get('top5'))} | {_pct(met.get('top10'))} | "
            f"{_pct(met.get('top20'))} |"
        )
    return "\n".join(lines)


def _cal_table(bins: list[dict[str, Any]]) -> str:
    if not bins:
        return "_No populated bins._"
    lines = ["| Bin | count | predicted | observed |", "|---|---|---|---|"]
    for b in bins:
        lines.append(
            f"| [{b['bin_low']}, {b['bin_high']}) | {b['count']} | "
            f"{b['predicted']} | {b['observed']} |"
        )
    return "\n".join(lines)


def _breakdown_table(breakdown: dict[str, dict[str, float]]) -> str:
    lines = ["| Group | n | log loss | Brier | ECE |", "|---|---|---|---|---|"]
    for g, m in breakdown.items():
        lines.append(
            f"| {g} | {m.get('n', 'n/a')} | {_f(m.get('log_loss'))} | "
            f"{_f(m.get('brier'))} | {_f(m.get('ece'))} |"
        )
    return "\n".join(lines)


def _team_stability_table(stab: dict[str, dict[str, float]]) -> str:
    lines = ["| Season | teams | mean attack std | mean defence std |", "|---|---|---|---|"]
    for season, m in stab.items():
        lines.append(
            f"| {season} | {m.get('n_teams', 'n/a')} | "
            f"{_f(m.get('mean_attack_std'))} | {_f(m.get('mean_defence_std'))} |"
        )
    return "\n".join(lines) if lines else "_None._"


def report_sections(results: dict[str, Any]) -> list[tuple[str, str]]:
    """Return ordered (heading, markdown-body) pairs for the report."""
    secs: list[tuple[str, str]] = []

    prov = results.get("data_provenance", {})
    secs.append(
        (
            "2. Dataset coverage & provenance",
            f"- **Provider**: `{prov.get('provider')}`\n"
            f"- **Data type**: {prov.get('data_type')}\n"
            f"- **Seasons loaded**: {', '.join(prov.get('seasons_loaded', []))}\n"
            f"- **Feature rows built**: {results.get('rows_built')}\n\n"
            "**Important caveat**: every season in this evaluation was generated by "
            "the mock historical provider. It is synthetic data, not real FPL/"
            "football history. Any numeric performance below is a test of the "
            "pipeline on generated data, NOT evidence of real-world predictive edge.",
        )
    )

    pv = results.get("pipeline_validation", {})
    secs.append(
        (
            "14. Pipeline validation",
            f"- Eligible (player, Gameweek) slots: **{pv.get('eligible_player_gameweeks')}**\n"
            f"- Featured rows produced: **{pv.get('featured_rows')}**\n"
            f"- Missing feature rows: **{pv.get('missing_rows')}**\n"
            f"- Data completeness: **{_pct(pv.get('data_completeness'))}**\n"
            f"- Temporal ordering: **{pv.get('temporal_ordering')}**\n"
            f"- Leakage test: **{pv.get('leakage_test')}**\n\n"
            f"> {pv.get('leakage_note')}\n\n"
            f"> {pv.get('db_temporal_policy_note')}",
        )
    )

    secs.append(
        (
            "3. Important synthetic-data limitation",
            "\nThe five available seasons come from `MockHistoricalDataProvider`. "
            "Points and minutes are generated from deterministic periodic formulas "
            "(e.g. points patterned by `gameweek mod 10`, minutes alternating "
            "0/90). This is not real football data and does not exhibit realistic "
            "player variance, fixture difficulty, ownership behaviour, or "
            "form/build-order structure.\n\n"
            "**Therefore:**\n"
            "- Model results here are **pipeline validation only**.\n"
            "- They must NOT be interpreted as establishing real FPL predictive edge.\n"
            "- Under **STEP 11** the recommendation prioritises integrating a real "
            "historical data source before any predictive-edge claims.",
        )
    )

    bas = results.get("baselines", {})
    agg = bas.get("aggregate", {})
    body = [
        "### Aggregate across primary evaluation period\n",
        _model_table(agg),
        "\n### Per-season\n",
    ]
    for season, models in bas.get("per_season", {}).items():
        body.append(f"\n**{season}**\n\n{_model_table(models)}")
    body.append(
        "\n> Note: the mock generator is season-invariant, so per-season numbers "
        "are identical across seasons by construction (synthetic-data artifact, "
        "see Section 13)."
    )
    secs.append(("5. Baseline results", "\n".join(body)))
    secs += _extra_sections(results)
    return secs


def _extra_sections(results: dict[str, Any]) -> list[tuple[str, str]]:
    secs: list[tuple[str, str]] = []

    mm = results.get("minutes", {})
    magg = mm.get("aggregate", {})
    body = [
        "### Aggregate\n",
        f"- n = {magg.get('n')}\n"
        f"- Start-probability log loss = **{_f(magg.get('start_log_loss'))}**\n"
        f"- Start-probability Brier = **{_f(magg.get('start_brier'))}**\n"
        f"- Start-probability ECE = **{_f(magg.get('start_ece'))}**\n"
        f"- 30+ min calibration ECE = **{_f(magg.get('cal_30_ece'))}**\n"
        f"- 60+ min calibration ECE = **{_f(magg.get('cal_60_ece'))}**\n"
        f"- Expected-minutes MAE = **{_f(magg.get('expected_minutes_mae'))}**\n"
        f"- Expected-minutes RMSE = **{_f(magg.get('expected_minutes_rmse'))}**\n",
        "\n### Start-probability calibration (10 bins)\n",
        _cal_table(magg.get("start_calibration", [])),
        "\n### 30+ minute probability calibration\n",
        _cal_table(magg.get("cal_30_calibration", [])),
        "\n### 60+ minute probability calibration\n",
        _cal_table(magg.get("cal_60_calibration", [])),
        "\n### Per-season\n",
    ]
    for season, m in mm.get("per_season", {}).items():
        body.append(
            f"**{season}**: n={m.get('n')}, start LL={_f(m.get('start_log_loss'))}, "
            f"start Brier={_f(m.get('start_brier'))}, start ECE={_f(m.get('start_ece'))}, "
            f"30+ ECE={_f(m.get('cal_30_ece'))}, 60+ ECE={_f(m.get('cal_60_ece'))}, "
            f"xMin MAE={_f(m.get('expected_minutes_mae'))}"
        )
    body.append("\n### Breakdown\n")
    bd = mm.get("breakdown", {})
    body.append("**Position**\n\n" + _breakdown_table(bd.get("position", {})))
    body.append("\n**Price range**\n\n" + _breakdown_table(bd.get("price_range", {})))
    body.append(
        "\n**Expected-minutes bucket**\n\n" + _breakdown_table(bd.get("minutes_bucket", {}))
    )
    body.append("\n### Simple-heuristic comparison (start probability)\n\n")
    hp = mm.get("heuristic_product", {})
    body.append(
        _breakdown_table(
            {
                "model": hp.get("model", {}),
                "prev_start_rate": hp.get("prev_start_rate", {}),
                "recent_start_rate": hp.get("recent_start_rate", {}),
            }
        )
    )
    body.append(
        f"\nExpected-minutes MAE: model={_f(hp.get('model_minutes_mae'))} vs "
        f"recent-minutes-average={_f(hp.get('minutes_avg_mae'))}"
    )
    secs.append(("6. Minutes model results", "\n".join(body)))

    tm = results.get("team_match", {})
    tma = tm.get("aggregate", {})
    eg_base = tm.get("expected_goals_baseline_mae", {})
    body = [
        f"Matches scored: **{tm.get('matches')}**\n",
        "### Aggregate\n",
        f"- WDL log loss = **{_f(tma.get('wdl_log_loss'))}**\n"
        f"- WDL Brier = **{_f(tma.get('wdl_brier'))}**\n"
        f"- Expected-goals MAE = **{_f(tma.get('expected_goals_mae'))}**\n"
        f"- Expected-goals RMSE = **{_f(tma.get('expected_goals_rmse'))}**\n"
        f"- Clean-sheet ECE = **{_f(tma.get('clean_sheet_ece'))}**\n"
        f"- Clean-sheet Brier = **{_f(tma.get('clean_sheet_brier'))}**\n",
        "\n### WDL base rates\n"
        f"home={_f(tm.get('wdl_baselines', {}).get('home'))}, "
        f"draw={_f(tm.get('wdl_baselines', {}).get('draw'))}, "
        f"away={_f(tm.get('wdl_baselines', {}).get('away'))}\n",
        f"\nExpected-goals league-avg baseline MAE = **{_f(eg_base.get('league_avg_mae'))}**\n",
        "\n### Team attack/defence stability (std of rolling strength, per season)\n",
        _team_stability_table(tm.get("team_stability", {})),
    ]
    secs.append(("7 & 8. Team model & match model results", "\n".join(body)))

    pp = results.get("player_pipeline", {})
    body = [
        "### Aggregate (A recent form / B minutes-adjusted / C fixture-adjusted / D integrated)\n",
        _model_table(pp.get("aggregate", {})),
        "\n### Per-season\n",
    ]
    for season, models in pp.get("per_season", {}).items():
        body.append(f"\n**{season}**\n\n{_model_table(models)}")
    body.append("\n### By position (aggregate)\n")
    for pos, models in pp.get("position", {}).items():
        body.append(f"\n**{pos}**\n\n{_model_table(models)}")
    body.append("\n### By price band (aggregate, model D)\n")
    for band, models in pp.get("price", {}).items():
        d = models.get("baseline_d", {})
        body.append(
            f"**{band}**: D n={d.get('n')}, MAE={_f(d.get('mae'))}, "
            f"Spearman={_f(d.get('spearman'))}"
        )
    secs.append(("9. Player expected-points results", "\n".join(body)))

    ab = results.get("ablations", {})
    body = []
    for name, pairs in ab.items():
        body.append(f"\n### {name}\n")
        for label, met in pairs.items():
            if isinstance(met, dict) and "mae" in met:
                body.append(
                    f"- **{label}**: MAE={_f(met.get('mae'))}, "
                    f"Spearman={_f(met.get('spearman'))}, "
                    f"top10={_pct(met.get('top10_capture'))}"
                )
            elif label == "delta_mae":
                body.append(f"- **Delta MAE**: {_f(met)}")
    secs.append(("11. Ablation tests", "\n".join(body)))

    cp = results.get("captain_proxy", {})
    vr = cp.get("vs_recent_form", {})
    rfc = cp.get("recent_form_captain", {})
    fbc = cp.get("fixture_baseline_captain", {})
    body = [
        f"Gameweeks evaluated: **{cp.get('n_gameweeks')}** (diagnostic only, not a "
        "final captain optimizer)\n",
        f"- Integrated-pipeline captain avg points = **{_f(vr.get('average_points'))}**\n"
        f"- Recent-form captain avg points = **{_f(rfc.get('average_points'))}**\n"
        f"- Fixture-baseline captain avg points = **{_f(fbc.get('average_points'))}**\n"
        f"- Integrated captain success rate vs recent-form = **{_pct(vr.get('success_rate'))}**\n"
        f"- Integrated captain points above baseline = **{_f(vr.get('points_above_baseline'))}**\n",
    ]
    secs.append(("10. Captain proxy", "\n".join(body)))
    return secs


def write_report(results: dict[str, Any], path: str | Path = REPORT_PATH) -> Path:
    """Write the markdown report file to disk."""
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# Phase 4.5 — Quantitative Edge Validation Report",
        "",
        f"_Generated {datetime.now().isoformat(timespec='seconds')}_",
        "",
        "## 1. Executive summary",
        "",
        "This milestone measured the existing prediction components against the "
        "available historical dataset. **The dataset is synthetic/mock data.** "
        "All results in this report are **pipeline validation**: they verify the "
        "pipeline runs, cutoffs work, ordering is leakage-free, and metrics are "
        "computable — they do NOT demonstrate real-world FPL predictive edge.",
        "",
    ]

    ordered = [
        "2. Dataset coverage & provenance",
        "3. Important synthetic-data limitation",
        "4. Data realism audit",
        "5. Baseline results",
        "6. Minutes model results",
        "7 & 8. Team model & match model results",
        "9. Player expected-points results",
        "10. Captain proxy",
        "11. Ablation tests",
        "12. Calibration",
        "13. Season stability",
        "14. Pipeline validation",
        "15. Predictive edge validation status",
        "16. Limitations",
        "17. KEEP / IMPROVE / DEPRIORITIZE decisions",
        "18. Recommended next step",
    ]
    secs = {h: b for h, b in report_sections(results)}
    secs["4. Data realism audit"] = (
        "The mock generator may favour certain model assumptions. "
        "Potential circularity / realism issues identified:\n\n"
        "- **Synthetic points from periodic formula**: FPL points are generated "
        "as `max(0, gw mod 10 - player_idx mod 3)` — a purely periodic signal "
        "repeating across the season and identical across seasons, NOT derived "
        "from football performance, form, or opponent quality. Any apparent "
        "'predictive' skill of form baselines here is an artifact of this "
        "synthetic periodicity.\n\n"
        "- **Synthetic minutes alternate 0/90**: minutes are `90 if "
        "(gw + player_idx) mod 2 == 0 else 0`. The MinutesModel's near-perfect "
        "start-probability calibration (ECE ~ 0) reflects this deterministic "
        "binary signal, not real rotation/lineup dynamics.\n\n"
        "- **Fixtures independent of strength**: fixture scores are "
        "`(fixture_index mod 5)` / `(2*fixture_index mod 4)`, independent of "
        "any team-strength concept. Match-model expected-goals error therefore "
        "cannot show real strength-based skill.\n\n"
        "- **Ownership/price synthetic**: selected_by_percent and price are "
        "linear functions of player index; they do not reflect real market "
        "behaviour.\n\n"
        "**Consequence**: results whose assumptions overlap these synthetic "
        "generators are marked **'Pipeline validation only'** and must not be "
        "read as predictive edge."
    )
    secs["12. Calibration"] = (
        "Calibration tables for the minutes model (start, 30+, 60+ "
        "probabilities) are reported in Section 6. On synthetic data, "
        "calibration quality only shows that the isotonic/regression machinery "
        "executes; it says nothing about real football probabilities."
    )
    secs["13. Season stability"] = (
        "Per-season tables are provided for the baselines, minutes model and "
        "match model. Cross-season differences are artifacts of the "
        "deterministic synthetic generator (which is season-invariant) and "
        "cannot be read as footballing season-to-season variability."
    )
    secs["15. Predictive edge validation status"] = (
        "**NOT ESTABLISHED.** Because all data is synthetic/generated, the "
        "project has NOT established a real-world FPL predictive edge. Model "
        "results on mock data must not be interpreted as evidence of real "
        "football predictive ability."
    )
    secs["16. Limitations"] = (
        "- Synthetic data: deterministic periodic point/minute generation.\n"
        "- No real team-structure or fixture-difficulty relationships.\n"
        "- Synthetic ownership does not reflect real market behaviour.\n"
        "- Unrealistically low player variance.\n"
        "- DB-level STRICT_REPRODUCIBILITY temporal policy not exercisable "
        "(mock provider omits available_at/ingested_at/deadline_time)."
    )
    secs["17. KEEP / IMPROVE / DEPRIORITIZE decisions"] = (
        "**KEEP (infrastructure)**: data-audit, uncertainty, pipeline "
        "validation, leakage-safe backtesting.\n\n"
        "**IMPROVE (not yet reliable)**: MinutesModel, baselines, "
        "PoissonMatchModel — technically sound, unproven on real data.\n\n"
        "**DEPRIORITIZE (complexity without demonstrated value on this data)**: "
        "components that add complexity without measurable improvement here, "
        "pending real-data re-validation."
    )
    secs["18. Recommended next step"] = (
        "**Do NOT start Phase 5 model development on this basis.** The "
        "infrastructure is sound but the dataset is synthetic. Prioritise "
        "integrating a REAL historical data source (real FPL API / results) and "
        "re-run this gate. The goal is a trustworthy real-data evaluation "
        "environment before claiming predictive edge.\n\n"
        "---\n\n"
        "_Classified overall as: **A. Pipeline validated, real predictive edge "
        "not yet testable** (pending real-data integration). Synthetic data "
        "cannot support classification B/C._"
    )
    for h in ordered:
        if h in secs:
            lines.append(f"## {h}")
            lines.append("")
            lines.append(secs[h])
            lines.append("")

    out.write_text("\n".join(lines), encoding="utf-8")
    return out
