"""Pydantic models for the Personalized Squad Decision Engine."""

from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field


class SquadStateCreate(BaseModel):
    """Request body for setting the user's squad state."""

    player_ids: list[int] = Field(
        ...,
        description="List of 15 player IDs in the user's squad.",
        min_length=15,
        max_length=15,
    )
    captain_id: int = Field(..., description="ID of the current captain.")
    vice_captain_id: int = Field(..., description="ID of the current vice-captain.")
    bank: float = Field(default=0.0, description="Available funds in millions.")
    free_transfers: int = Field(default=1, ge=0, description="Number of free transfers available.")
    chips_available: list[str] = Field(
        default_factory=lambda: ["wildcard", "free_hit", "bench_boost", "triple_captain"],
        description="List of chips still available to play.",
    )
    gameweek: int = Field(..., gt=0, description="Current FPL gameweek.")
    player_positions: dict[int, int] | None = Field(
        default=None,
        description="Optional mapping of player_id -> position_code (1=GK, 2=DEF, 3=MID, 4=FWD).",
    )
    player_prices: dict[int, float] | None = Field(
        default=None,
        description="Optional mapping of player_id -> price in millions.",
    )
    player_teams: dict[int, int] | None = Field(
        default=None,
        description="Optional mapping of player_id -> team_id.",
    )


class SquadStateResponse(SquadStateCreate):
    """Response body for retrieving the current squad state."""

    updated_at: datetime | None = None


class TransferPlan(BaseModel):
    """Structured transfer recommendation from the optimizer."""

    action_type: str
    transfers_in: list[int] = Field(default_factory=list)
    transfers_out: list[int] = Field(default_factory=list)
    hit_cost: int = 0
    expected_gain: float = 0.0
    probability_positive: float = 0.0
    confidence: float = 0.0
    main_reason: str = ""
    main_risk: str = ""


class ChipRecommendation(BaseModel):
    """Structured chip recommendation from the optimizer."""

    chip_name: str | None = None
    expected_gain: float = 0.0
    confidence: float = 0.0
    main_reason: str = ""


class CaptainRecommendation(BaseModel):
    """Structured captain recommendation from the optimizer."""

    player_id: int
    expected_points: float = 0.0
    expected_gain: float = 0.0
    probability_positive: float = 0.0
    confidence: float = 0.0
    main_reason: str = ""
    main_risk: str = ""


class DecisionReport(BaseModel):
    """Personalized decision report generated by the DecisionOptimizerBridge."""

    generated_at: datetime = Field(default_factory=datetime.utcnow)
    gameweek: int
    starting_xi: list[int] = Field(default_factory=list)
    bench_order: list[int] = Field(default_factory=list)
    captain: CaptainRecommendation | None = None
    vice_captain: int | None = None
    transfer_plan: TransferPlan | None = None
    chip_recommendation: ChipRecommendation | None = None
    meta: dict[str, Any] = Field(default_factory=dict)
