"""Pydantic models for the Personalized Squad Decision Engine."""

from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

#: A valid, ready-to-paste example body so Swagger (and the squad endpoint's
#: ``Try it out`` button) shows integer player IDs instead of the default
#: ``additionalProp`` placeholders.
_SQUAD_EXAMPLE = {
    "player_ids": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    "captain_id": 3,
    "vice_captain_id": 11,
    "bank": 0.5,
    "free_transfers": 1,
    "chips_available": ["wildcard", "free_hit", "bench_boost", "triple_captain"],
    "gameweek": 8,
    "player_positions": {1: 1, 2: 2, 3: 3, 4: 1, 11: 4},
    "player_prices": {1: 5.0, 2: 5.5, 3: 12.5, 11: 11.0},
    "player_teams": {1: 3, 2: 3, 3: 1, 11: 8},
}


class SquadStateCreate(BaseModel):
    """Request body for setting the user's squad state."""

    model_config = ConfigDict(json_schema_extra={"example": _SQUAD_EXAMPLE})

    player_ids: list[int] = Field(
        ...,
        description="List of 15 player IDs in the user's squad.",
        min_length=15,
        max_length=15,
        examples=[_SQUAD_EXAMPLE["player_ids"]],
    )
    captain_id: int = Field(
        ..., description="ID of the current captain.", examples=[_SQUAD_EXAMPLE["captain_id"]]
    )
    vice_captain_id: int = Field(
        ...,
        description="ID of the current vice-captain.",
        examples=[_SQUAD_EXAMPLE["vice_captain_id"]],
    )
    bank: float = Field(
        default=0.0, description="Available funds in millions.", examples=[_SQUAD_EXAMPLE["bank"]]
    )
    free_transfers: int = Field(
        default=1, ge=0, description="Number of free transfers available.", examples=[1]
    )
    chips_available: list[str] = Field(
        default_factory=lambda: ["wildcard", "free_hit", "bench_boost", "triple_captain"],
        description="List of chips still available to play.",
        examples=[_SQUAD_EXAMPLE["chips_available"]],
    )
    gameweek: int = Field(
        ..., gt=0, description="Current FPL gameweek.", examples=[_SQUAD_EXAMPLE["gameweek"]]
    )
    player_positions: dict[int, int] | None = Field(
        default=None,
        description="Optional mapping of player_id -> position_code (1=GK, 2=DEF, 3=MID, 4=FWD).",
        examples=[_SQUAD_EXAMPLE["player_positions"]],
    )
    player_prices: dict[int, float] | None = Field(
        default=None,
        description="Optional mapping of player_id -> price in millions.",
        examples=[_SQUAD_EXAMPLE["player_prices"]],
    )
    player_teams: dict[int, int] | None = Field(
        default=None,
        description="Optional mapping of player_id -> team_id.",
        examples=[_SQUAD_EXAMPLE["player_teams"]],
    )
    is_demo: bool = Field(
        default=False,
        description="True when the squad was generated by the demo builder "
        "rather than imported from a real FPL account.",
        examples=[False],
    )
    session_id: str | None = Field(
        default=None,
        description="Optional session key isolating this squad row. For "
        "per-user isolation pass the user's FPL entry_id here. When omitted "
        "the route requires the query param instead.",
        examples=["1234567"],
    )


class SquadStateResponse(SquadStateCreate):
    """Response body for retrieving the current squad state."""

    updated_at: datetime | None = None


class TransferPlan(BaseModel):
    """Structured transfer recommendation from the optimizer."""

    action_type: str
    transfers_in: list[int] = Field(default_factory=list)
    transfers_out: list[int] = Field(default_factory=list)
    hit_cost: int = 0
    expected_gain: float = 0.0
    probability_positive: float = 0.0
    confidence: float = 0.0
    main_reason: str = ""
    main_risk: str = ""


class ChipRecommendation(BaseModel):
    """Structured chip recommendation from the optimizer."""

    chip_name: str | None = None
    expected_gain: float = 0.0
    confidence: float = 0.0
    main_reason: str = ""


class CaptainRecommendation(BaseModel):
    """Structured captain recommendation from the optimizer."""

    player_id: int
    expected_points: float = 0.0
    expected_gain: float = 0.0
    probability_positive: float = 0.0
    confidence: float = 0.0
    main_reason: str = ""
    main_risk: str = ""


class PlayerDetail(BaseModel):
    """Enriched player details for dashboard rendering.

    Returned by ``GET /api/v1/decisions`` so the frontend can render photos,
    badges, prices, and expected points without a separate player lookup.
    """

    id: int
    web_name: str
    team: int | None = None
    position: int | None = None
    price: float | None = None
    #: FPL element code for Premier-League-CDN photo URLs.
    code: int | None = None
    #: Expected points (xPTS) for the current gameweek.
    expected_points: float | None = None
    #: Which chain level produced the xPTS (``model-backtest``, ``baseline-model``,
    #: ``pre-season-proxy-v2``). ``None`` when the player is absent from the chain.
    prediction_source: str | None = None
    #: Evidence tier behind the number (``historical-backtest``,
    #: ``ingested-gameweek-history``, ``heuristic-proxy-enriched``).
    data_quality: str | None = None
    #: Estimated minutes for the gameweek (chain's per-player estimate).
    minutes_estimate: float | None = None
    #: Probability the player starts the match.
    start_prob: float | None = None
    #: Last-season xG/90 from Understat — ``None`` for non-Understat-matched players.
    xg: float | None = None
    #: Last-season xA/90 from Understat — ``None`` for non-Understat-matched players.
    xa: float | None = None
    #: xPTS breakdown: base(price) + xG/xA term + market term + weather term.
    #: ``None`` when the resolved chain level does not produce a breakdown.
    xpts_breakdown: dict[str, float] | None = None


class DecisionReport(BaseModel):
    """Personalized decision report generated by the DecisionOptimizerBridge."""

    generated_at: datetime = Field(default_factory=datetime.utcnow)
    gameweek: int
    starting_xi: list[int] = Field(default_factory=list)
    bench_order: list[int] = Field(default_factory=list)
    captain: CaptainRecommendation | None = None
    vice_captain: int | None = None
    transfer_plan: TransferPlan | None = None
    chip_recommendation: ChipRecommendation | None = None
    #: Enriched per-player details keyed by player ID (string for JSON).
    #: Includes web_name, team, position, price, code, and expected_points.
    players: dict[str, PlayerDetail] = Field(default_factory=dict)
    meta: dict[str, Any] = Field(default_factory=dict)

class FromFplResponse(BaseModel):
    """Response for ``POST /api/v1/squad/from-fpl``.

    Returns the persisted squad plus a display-name map keyed by the stored
    player IDs (FPL element IDs) so the dashboard can render names instead of
    raw integers.
    """

    squad: SquadStateResponse
    player_names: dict[int, str] = Field(
        default_factory=dict,
        description="Map of stored player_id -> display name (web_name).",
    )
    entry_name: str | None = Field(
        default=None, description="Manager's FPL team name, if available."
    )
    gameweek: int = Field(..., description="Gameweek the squad was imported for.")
    is_demo: bool = Field(
        default=False,
        description="True when the squad was built by the demo builder.",
    )
    #: When the import was queued (rate-limited), the sync status message.
    sync_status: str | None = Field(
        default=None,
        description="Human-readable sync status when the import was queued.",
    )
